[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "apuestas-rentables-457423"
private_key_id = "4ba4246c61b08311b0fa9976a5d7a34ad34e1e11"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEowIBAAKCAQEApM4cWe7Y8VV3sbEBW8MpTx1yq9JWJKIsbzyEnPLmCkZK6ZHF
my9y9VluJm2v6kFZOPsfOTkK1bDCDQAZpy9UPYzRH6FeozMz1UhSzBTAXT2oOnn5
uAWe/7Zsn8kAzUlTOf+/WPCzybnMiCph7VoapR8YUEoGNM7UVzIkYqyzcTKKUMd1
NP2nUnhv+EjTcHPo0j9P3GhMAsrHVL5KyEm4/q1D4dSACx97j4fKX4uwYb75l8wX
PXV3ZXNmvC6tr4j4gcQdpIDFTYarMLSn5/4+b9A0hwlnlGdJIQa9v9yC1kQKP04k
kZ/WiNUCnyT3zEQ78aNNOiUNz4uM8CrX6IbcrwIDAQABAoIBAQCZCWMyUgEiKwUu
jG9UJIp2CrF9GfZffpvHhRgxH+OekTAAMnzm5C3fOGxdiDX0sEABgvLRqjv5ZtIk
QQb6I8bqTLgub9+PqIWEYtJpQG5MkQ3jc6pp4NSJtH4D7epD2eHjxgx3zEJJuBVD
fpIE1HQKx9zUPj3S2TWazzyAHZqek7KR8op7If3HQkkuF1XoKTwG6lyfJLM1ufl9
R+BZyK9dMi0N3kxNc+fTGeYFPIYXeRZ7z8o9ULaVXg2CInP+aAa0aErF5qvGE2hD
KleNDBbmLErb29zxyOH9OBg3+4EIdC2ZcwLb66FYMBz2/2hHRnXhsfULNH9DoUcg
DUy66kFBAoGBAOyHEdjKryY4yKaUbJzswXZPmh6iGuV+qu6V3RrGULf1b03klCdz
N9UnIxyw/XIVqQQJg0/Ydn3GpVnJmwtAB/vOYrc+BtSt5cy8NBMuFy65aTZKDnFt
7AzHVKkiG63M/Cg9GXYDLsRYSE50ZLb6jCEubNEK1VEZssJrzkN+sdWFAoGBAMXP
Y5WmWeopas12jSgzyb5TD22bUTK1Y29xgXtEu5qfbxd8ahOEIQJgM3z8V7/xdoUX
4FL19MkNJSQAv2QLiqAYGTT3DPD4bzYeHQAnocWwR1TDsf2oAZvPvMF2nNMLkhIN
TrhYkPPaAh5mt+VX2MYc8LK9guTZv1D1VPLsW3DdAoGAGs5wJNDoxmjAnUR+Hgt1
bXwtdDyzjUF7C9s8VHzB6mZaqej53mnmQov+uwNVTeffHScPBkGV29K2WB7k68Jo
fa+Ey0UL2fL9mDbkJxPGcD9ZdwS+Yq7JkZq3AtEx0w2QHTkQ8UN7puogOojZXvEj
ZojZG+4D9kXsfIu9a1sLPlUCgYB61LP3tdWxNUboPzM2FhM9WmS3QgdkSvQ+2q1A
JgbMLxOH8rbAPhCbWyU4f4a/RHdBW1DqDvhTGuIJRMjDNlgsLsfPVz9w9U+aI0hK
rXpjOWHzLFeM7lfloTqPrlbTPK6E6X07R3zLrknYbwrulSzs8dvHPaNS4ZKzVmqR
7KZrUQKBgHwAtcuu7TZjX9PBsTkzn06flVJ4ZWSXZVhD6i0aKVYXs23xUFiS4sWY
w53xqLd8CB6JWHMtxAlIXILcPO2WyDQPMZh8eMv2QqtFr8F7OpQDJTnyRxdg9Rnx
hZuAsuOvUPf5Wkox6TD95bAxRpZW7ksn6E2MOlWw5kTk3F5zdbeg
-----END PRIVATE KEY-----"""
client_email = "apuestas-rentables-457423@apuestas-rentables-457423.iam.gserviceaccount.com"
client_id = "117189961808771399924"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/apuestas-rentables-457423%40apuestas-rentables-457423.iam.gserviceaccount.com"
