GOOGLE_CREDS_JSON = """
{
  "type": "service_account",
  "project_id": "apuestas-rentables-457423",
  "private_key_id": "b71b68baadf6bfb19f6c34326733168cd097b4b3",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDgB9CVpGpQycYh\\n... (continúa aquí tu clave privada completa escapada con \\n)\\n-----END PRIVATE KEY-----\\n",
  "client_email": "apuestas-rentables@apuestas-rentables-457423.iam.gserviceaccount.com",
  "client_id": "112222713447300448374",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/apuestas-rentables%40apuestas-rentables-457423.iam.gserviceaccount.com"
}
"""
